### ISSUE TITLE
Need a better project structure

### ISSUE THREAD

**Issue by ppamorim** [Quinny898/PersistentSearch#1]

**Comment by Quinny898** [comment]
What would you suggest?

**Comment by MichaelEvans** [comment]
@Quinny898 I assume this is about gradle build support (and the newer directory structure that usually goes with it)

**Comment by Quinny898** [comment]
Ah, well I build in the non-gradle eclipse (I prefer it over AS), so it would actually break support for my own projects unfortunately

**Comment by MichaelEvans** [comment]
Someone else should be able to add gradle support with the existing structure.

**Comment by Quinny898** [comment]
Merged @MichaelEvans gradle support
