### ISSUE TITLE
Android studio rebuild project Could not find com.quinny898.library.persistentsearch:library:1.1.0-SNAPSHOT.

### ISSUE THREAD

**Issue by harunkandroid** [Quinny898/PersistentSearch#105]
I follow your instructions in readme file. Also i looked at your sample project. i m adding dependecies and maven but. error occurs when i rebuild project

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.quinny898.library.persistentsearch:library:1.1.0-SNAPSHOT.
     Searched in the following locations:
         https://jcenter.bintray.com/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/maven-metadata.xml
         https://jcenter.bintray.com/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.pom
         https://jcenter.bintray.com/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.jar
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/android/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/android/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.pom
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/android/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.jar
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/google/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/maven-metadata.xml
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/google/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.pom
         file:/C:/Users/harun/AppData/Local/Android/sdk/extras/google/m2repository/com/quinny898/library/persistentsearch/library/1.1.0-SNAPSHOT/library-1.1.0-SNAPSHOT.jar
     Required by:
         lok:app:unspecified

**Comment by TriangleYJ** [comment]
i have same problem :(

**Comment by phamvansy** [comment]
Android Studio: Add the Sonatype repository if you have not already:

maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
Import it as a dependency:

compile 'com.quinny898.library.persistentsearch:library:1.1.0-SNAPSHOT'


And in AndroindManifest add: android:allowBackup="true"

**Comment by agungsb** [comment]
I faced the same problem but I managed to solve the problem by this solution:

http://stackoverflow.com/questions/22175907/cant-import-project-to-android-studio

**Comment by harunkandroid** [comment]
i found the solution. In android studio i have two repositories tag in build.gradle(project:app) i changed both repositories. So here is build.gradle file


buildscript {
    repositories {

        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
