### ISSUE TITLE
Implemented Google Voice Search gives two result

### ISSUE THREAD

**Issue by ShreyashPromact** [Quinny898/PersistentSearch#13]
I have try to search "Hello" with Google Voice Search but it gives me two result as "hello hello".

Please check below image and try same with the app.
![device-2015-03-25-121312](https://cloud.githubusercontent.com/assets/8598335/6819535/6830cc9e-d2e8-11e4-9f10-75af89c0b13b.png)

**Comment by Quinny898** [comment]
This is google search results, nothing much I can do here. What it returns is what it returns.

**Comment by ShreyashPromact** [comment]
Please check the apps given by google (https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox) or any other google app or the example that has implementation of the Voice Search. It gives only one record at a time, not multiple records. So please look at it and update your app accordingly.

I suggest to check twice and thrice instead of saying "What it returns is what it returns".

Sincerely,
Shreyash.

**Comment by Quinny898** [comment]
I mean what it returns it returns. Google does the voice control, not me, I just parse the "best" result it gives back

**Comment by ShreyashPromact** [comment]
Ok. but what i mean is, just parse first record and show it to the user as results. Not all. That way user can have what he want to search and not the words compare to it. That's what i mean. Rest up to you.

**Comment by ShreyashPromact** [comment]
Hi Quinny,

I just come to know from which method there is an issue of voice search. I dont know how to fork, just want you to inform and update the same so that other user don't have such issue.

Please update the method of populateEditText in SearchBox class.
Update it as below:

/***
	 * Populate the searchbox with words, in an arraylist. Used by the voice input
	 * @param matches
	 */
	public void populateEditText(ArrayList<String> matches) {
		toggleSearch();
		String text = "";
		/*for (int x = 0; x < matches.size(); x++) {
			text = text + matches.get(x) + " ";
		}*/
		text = matches.get(0);
		setSearchString(text);
		search(text);
	}

Now, try it.

Note: Google gives all the possible result based on the voice. Its accuracy is higher to lower. So you can take first result and show it to user.

Please let me know if there is anything wrong from this..


Sincerely,
Shreyash.
