### ISSUE TITLE
startVoiceRecognitionActivity(activity); problem

### ISSUE THREAD

**Issue by Xpak** [Quinny898/PersistentSearch#16]
for example if i say "hi" it returns "hi high jai jaime hay" , and so all

my application language is Spanish

**Comment by AkiraSan83** [comment]
same here...

language italian

**Comment by Quinny898** [comment]
Can someone test what happens if you say multiple words?

**Comment by Xpak** [comment]
the same, That creates a paragraph of words ,
My solution was to delete the button was not very important in my application

sorry for my English

**Comment by Quinny898** [comment]
This was actually a simple fix:
for (int x = 0; x < matches.size(); x++) {
	text = text + matches.get(x) + " ";
}
is now:
text = text + matches.get(0);

Will be in the next update

**Comment by kunalshdr** [comment]
Is this pushed? I'm still facing the same issue.

**Comment by Quinny898** [comment]
Fixed in update
