### ISSUE TITLE
Closing Animation played twice

### ISSUE THREAD

**Issue by jnsone11** [Quinny898/PersistentSearch#19]
I had an issue that closing animation was played twice.
Solution was to set the following:

getActivity().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING);

Adjust resize / pan will reproduce the issue if you have content that might get pushed up like a tabhost.

You might consider adding this information to the readme.

**Comment by iraupph** [comment]
+1. This helps, but a library-side correction would be more appreciated.

**Comment by Quinny898** [comment]
I think I fixed this in the update, comment if not
