### ISSUE TITLE
How to lost focus

### ISSUE THREAD

**Issue by djyde** [Quinny898/PersistentSearch#22]
There is a ScrollView and a Searchbox, and how can I make the Searchbox lost focus when I scroll the ScrollView?

**Comment by djyde** [comment]
Oh i had found the solution

**Comment by Zaitungtung** [comment]
Hey @djyde , how did you solve the problem ?

**Comment by djyde** [comment]
@Zaitungtung I set a opacity view and when it was onClick, it would unvisable and toggle the searchbox
