### ISSUE TITLE
How check: IsSeachOpen

### ISSUE THREAD

**Issue by objaa** [Quinny898/PersistentSearch#25]
Hello, how i can check state seach? (open\close)

**Comment by MinsungHuh** [comment]
SearchBox.setSearchListener( SearchListener );

@Override
public void onSearchOpened() {}

@Override
public void onSearchCleared() {}

@Override
public void onSearchClosed() {}

@Override
public void onSearchTermChanged() {}

@Override
public void onSearch(String s) {}
