### ISSUE TITLE
Multiple onSearchTermChanged

### ISSUE THREAD

**Issue by co4uhutejib** [Quinny898/PersistentSearch#26]
Hello.
I try to use library. And after each close searching widget I get one extra onSearchTermChanged event. I think it because of openSearch method calling every time:
```java
search.addTextChangedListener(new TextWatcher() {
...
});
```

**Comment by iraupph** [comment]
You are correct, moving this code block to the constructor fixed this problem. Maybe I'll make a pull request for this later.

**Comment by Quinny898** [comment]
Fixed I think
