### ISSUE TITLE
How to: not show the suggestions in opening the search

### ISSUE THREAD

**Issue by Xpak** [Quinny898/PersistentSearch#27]
Search autocomplete properly, but i do not need the initial suggestions (when the EditText is empty )

how can i do this? 

thx in advance !

**Comment by stripathi669** [comment]
+1 for this issue.

**Comment by Quinny898** [comment]
Either skip this or pass an empty arraylist:
/***
	 * 
	 * Set the results that are shown (up to 5) when the searchbox is opened with no text 
	 * @param results Results
	 */
	public void setInitialResults(ArrayList<SearchResult> results){
		this.initialResults = results;
	}
