### ISSUE TITLE
Search term overlaps delete button

### ISSUE THREAD

**Issue by randombyte-developer** [Quinny898/PersistentSearch#28]
![device-2015-06-06-183039](https://cloud.githubusercontent.com/assets/10366256/8020482/7dba3be2-0c7a-11e5-9747-e33549bf385a.jpg)
As you can see, the search term overlaps the delete button. So, for me the lib is sadly unuseable.

**Comment by djyde** [comment]
![](http://ww4.sinaimg.cn/large/62580dd9jw1esuxwe88i0j20u01hcmyo.jpg)

I did not have this problem, could you show me your code?

**Comment by randombyte-developer** [comment]
<com.quinny898.library.persistentsearch.SearchBox
            android:layout_width="300dp"
            android:layout_height="wrap_content"
            android:layout_marginTop="48dp"
            android:layout_centerHorizontal="true"
            android:id="@+id/search_text"
            android:inputType="text"
            android:hint="@string/search_text_hint"/>

and only
-voice recognition
-search listener
-setLogoText
-menu visibility(invisible)

**Comment by djyde** [comment]
Sorry, I had tried some time but still cannot reappear the bug.

**Comment by randombyte-developer** [comment]
![device-2015-06-06-222540](https://cloud.githubusercontent.com/assets/10366256/8021325/2000ca22-0c9b-11e5-81fb-99aacecda1c6.jpg)
How does it look like on you device? btw the margin at the bottom belongs to a view below the SearchBox.

**Comment by randombyte-developer** [comment]
@Quinny898 What do you think is the problem?

**Comment by Quinny898** [comment]
I have not seen this issue, and I assume you fixed it in #39 anyway?

**Comment by randombyte-developer** [comment]
I didn't tried.

**Comment by randombyte-developer** [comment]
https://github.com/randombyte-developer/lmgtfy-App/blob/cbe5592864ca2761b7f795b70145b6f1d00f8f7c/app/src/main/res/layout/activity_main.xml#L23
You can clone and compile. Still occurs.
