### ISSUE TITLE
SearchView shrinks

### ISSUE THREAD

**Issue by randombyte-developer** [Quinny898/PersistentSearch#29]
https://youtu.be/47ydHVHj5MI

As you can see, the SearchView shrinks at the bottom when you touch it the first time.

**Comment by djyde** [comment]
The reason why SearchView shrinks because when the Menu icon view has gone, the padding of the view was gone, too.

To solve this problem, you could use `searchbox.setMenuVisibility(View.INVISIBLE)` instead of `searchbox.setMenuVisibility(View.GONE)`

**Comment by randombyte-developer** [comment]
Thank you!
