### ISSUE TITLE
Remove the MaterialMenu dependency

### ISSUE THREAD

**Issue by lynfogeek** [Quinny898/PersistentSearch#3]
I think this dependency is really limiting. 
In your example (gif) with the reveal activity, the effect doesn't look nice because the hamburger icon appear from nowhere to be transformed into the back arrow.

The `SearchListener` is enough to let people implement the Material Menu if they want to.

**Comment by Quinny898** [comment]
If you don't want it, create a fork and remove it. I'm keeping it as close to the original as possible.
