### ISSUE TITLE
Error in adding as a gradle dependence

### ISSUE THREAD

**Issue by samerzmd** [Quinny898/PersistentSearch#30]
compile 'com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT'

Error:(27, 13) Failed to resolve: com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT

**Comment by Quinny898** [comment]
Have you added 
maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
to the gradle file too?

**Comment by wayne1203** [comment]
Thanks for your library, but I have some problem about the dependence.
I added 
maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }

But still have Error:(34, 13) Failed to resolve: com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT problem.

Is it have some misunderstanding with me??

**Comment by skyplor** [comment]
Check out the sample build.gradle provided. Take note to have the repositories at the root of the build.gradle file like so:

repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    mavenCentral()
}

apply plugin: 'com.android.application'

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
}
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {...}
}
