### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by herriojr** [Quinny898/PersistentSearch#31]
Maybe I have a misunderstanding, but I'm trying to style the color of the material menu button inflated by this library, but I'm having a hell of a time.  There is an internal inflation of the material menu, and i want to change it's color for the up/menu button via "mm_color" -- I tried setting the style on the SearchBox to use the following style, but it doesn't work:

values/styles.xml
```xml
...
    <style name="SearchStyle">
        <item name="mm_color">@color/white</item>
    </style>
...
```

values/layout/my_layout.xml
```xml
...
<com.quinny898.library.persistentsearch.SearchBox android:id="@+id/searchbox"
            style="@style/SearchStyle"
            android:layout_width="wrap_content"
            android:layout_height="60dp"
            android:layout_alignParentTop="true"
            android:visibility="gone" />
...
```

**Comment by Quinny898** [comment]
Try applying the style in Java using the material menu:
searchBox.findViewById(R.id.material_menu_button)

**Comment by herriojr** [comment]
Thanks, I'll try that out.
