### ISSUE TITLE
Search Results Population

### ISSUE THREAD

**Issue by herriojr** [Quinny898/PersistentSearch#32]
The problem with the current implementation is it does the filtering internal to the SearchBox -- this isn't very good when the search needs to go against a server.  The other issue is the search depends on the Text itself being a match AT THE BEGINNING, which may not be true and is a case-by-case basis.  What if I were searching for a genre?  I may want to populate the list with movies in that genre. Another issue is the results are limited to a set of 5 items.  This is an arbitrary number.  I'm going to try and address some of this and do a pull request.

**Comment by stripathi669** [comment]
+1 for the same issue.

**Comment by Quinny898** [comment]
You can now use your own filter algorithm, which should fix this (see #37)
