### ISSUE TITLE
Conflicts with CircularReveal library

### ISSUE THREAD

**Issue by iraupph** [Quinny898/PersistentSearch#35]
Hello, I've found that if I have your library and the [CircularReveal](https://github.com/ozodrukh/CircularReveal) dependency in my project I get some `dex finished with non-zero exit value 2` errors when building it.
Trying to fix this, I discovered that you also use this library in your project but instead of adding it to your gradle dependencies you copied it directly in your source code packages.
By removing that code, adding a dependency in your project and a exclusion rule on mine, I've been able to build and use your library successfully.
Maybe you could improve this officially (or maybe I can make a pull request later) to avoid problems for other people.

**Comment by Quinny898** [comment]
Fixed in the update
