### ISSUE TITLE
Single search activity

### ISSUE THREAD

**Issue by VihaanVerma89** [Quinny898/PersistentSearch#40]
First of all thanks for this awesome library :) . 

I plan on creating a single search activity for app. All activities will have the search icon in the action bar
![activity](https://cloud.githubusercontent.com/assets/4493362/8494757/a267e460-2185-11e5-8845-e2e20600bb19.png)

Upon clicking this search icon from any of the activities the main search activity will open up like below
![search_activity](https://cloud.githubusercontent.com/assets/4493362/8494777/cc7c3ed6-2185-11e5-8e27-2a9c7aad5252.png)
The search activity has transparent background and opens up without animation making the user feel that it has opened up in the same activity. This way all my search related code remains in the Search activity and not scattered in every activity that integrates PersistentSearch .

The problem is that I m not able to display the expanded search view automatically. What basically needs to happen is that when the user clicks on search icon from any activity , the search activity opens  up and expands the search box without user having to click the search icon. I tried calling the openSearch function the moment the activity gets created but it only shows the search box and not the options since the menuButton is null in the revealFromMenuItem function call. Manually clicking the search icon in the sample "reveal activity" works find but how can the same thing be shown automatically when the "reveal activity" starts?

**Comment by Quinny898** [comment]
Bit of a hacky way, but have you tried "clicking" the menu icon in code?
http://stackoverflow.com/questions/26015424/programatically-fire-action-bar-menu-item-in-android

**Comment by Quinny898** [comment]
I'm going to close this because of the time without a reply
