### ISSUE TITLE
SearchBox.measure

### ISSUE THREAD

**Issue by o2genum** [Quinny898/PersistentSearch#43]
If I execute this code multiple times:

            mSearchBox.measure(View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED),
                    View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED));
            mSearchBoxHeight = mSearchBox.getMeasuredHeight();

The SearchBox behaves badly: on different devices in a different way, but the box generally shrinks on search close. Now I measure it only once and it's ok, but i think measurement shouldn't affect the box badly.

**Comment by Quinny898** [comment]
The box does shrink when it closes, because it's just a view with a listview that pops up. I can't really fix that or the initial values would be huge and there'd be an empty view blocking clicks
