### ISSUE TITLE
Allow match suggestions at any place

### ISSUE THREAD

**Issue by CoericK** [Quinny898/PersistentSearch#44]
Hey amazing library but i would like to know if i can make it work to filter results without matching the suggestions from the start, handling my own criteria to filter the suggestions, i mean:
If i type:
A, it  would go and search to my API and it would return:
Alejandro
Carla
Maria
but it is just showing Alejandro, cuz its filtering from start, if i type ar, it should show Carla, and Maria, can i make this amazing library work this way?

**Comment by randombyte-developer** [comment]
#37 gives us the ability to do that if it gets merged.

**Comment by Quinny898** [comment]
#37 was also merged and is in the update
