### ISSUE TITLE
Add optional animation like latest Google Play

### ISSUE THREAD

**Issue by tajchert** [Quinny898/PersistentSearch#5]
Way of hide/show bar when it is not necessary to the right side of screen with animation.
Like below on Movies&TV screen.
![animation](http://www.androidpolice.com/wp-content/uploads/2015/02/nexus2cee_toolbar1.gif)

**Comment by djyde** [comment]
Hey @tajchert , how did you solve this problem then ?

**Comment by tajchert** [comment]
@djyde I run it and realized that it is already there - I missed it in Gif example.

**Comment by djyde** [comment]
@tajchert and did u know how to lost focus from it? ​I use clearFocus() and it didnt work. https://github.com/Quinny898/PersistentSearch/issues/22
