### ISSUE TITLE
the dependence is not working   

### ISSUE THREAD

**Issue by osama-raddad** [Quinny898/PersistentSearch#50]
i have this error when i add the  dependence line compile 'com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT' :

Error:(61, 13) Failed to resolve: com.quinny898.library.persistentsearch:library:1.0.0-SNAPSHOT
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by harishannam** [comment]
Same for me too

**Comment by Quinny898** [comment]
Well it's on Sonatype and sonatype is up, so it must be your config

**Comment by bropane** [comment]
Add this to your app build.gradle
```java
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by Quinny898** [comment]
That is also in the readme. Following that is your best bet
