### ISSUE TITLE
Gradle build not updated

### ISSUE THREAD

**Issue by SuperiorJT** [Quinny898/PersistentSearch#53]
I noticed that you merged some new features into the library on GitHub, but I'm sure a lot of us are using Gradle in order to obtain it. Could you please update the Gradle build so that we can use these new features?

**Comment by Quinny898** [comment]
I am aware of this, and am waiting for #39 to be updated before merging and uploading

**Comment by fbvictorhugo** [comment]
@Quinny898 #39 'his branch is up-to-date with the base branch', and when compile from Gradle is available?
:)

**Comment by quanturium** [comment]
@Quinny898 Same here, would love to have an up to date version on sonatype. The current one has a lot of bugs that have been fixed on this repo.

**Comment by Glurt** [comment]
+1 this, I would like to use this library in my app but the gradle build is out of date which is putting me off.

**Comment by xXProdoxX** [comment]
Same here. I wanted to use the setLogoTextColor function but it's not updated on Gradle as yet. Please let me know when it is updated.

**Comment by quanturium** [comment]
@Quinny898 I really need an updated version of this library on maven. Would you mind if I fork the project and publish it on maven on my own?

**Comment by Quinny898** [comment]
Done, sorry for the huge delay, loads of things been happening
