### ISSUE TITLE
Bug in hideCircularly method

### ISSUE THREAD

**Issue by oneassasin** [Quinny898/PersistentSearch#57]
295 line in SearchBox class ([link](https://github.com/Quinny898/PersistentSearch/blob/master/library/src/main/java/com/quinny898/library/persistentsearch/SearchBox.java#L295)) 
```
display.getSize(size);
``` 
Call of this method requires API level 13, but in project min API level is 11.

**Comment by Quinny898** [comment]
Fixed in update
