### ISSUE TITLE
backport to Android 2.1+

### ISSUE THREAD

**Issue by croccio** [Quinny898/PersistentSearch#6]
backport to Android 2.1+ please

**Comment by Quinny898** [comment]
Depends what you want in a backport, everything except the dropdown animation is easily possible. I might also be changing that to be smoother, but would you need that?

**Comment by patelakshay13890** [comment]
I also want this to backport to 3.0

**Comment by Quinny898** [comment]
It already is compatible with 3.0 to my knowledge

**Comment by Quinny898** [comment]
Because of the fact that it's suggested that really you shouldn't even be supporting Android 2.3 any more, I'm no longer considering this
