### ISSUE TITLE
Hide hamburger Icon 

### ISSUE THREAD

**Issue by AmirHadifar** [Quinny898/PersistentSearch#60]
Hi , Is it possible to Hide Hamburger Icon  Or Back Icon ?

**Comment by TheLoyalCruel** [comment]
this is my question too!

**Comment by rushabh358** [comment]
I also want to do the same.But No such method.

**Comment by mstrengis** [comment]
mSearch = (SearchBox) findViewById(R.id.searchbox);
 mSearch.setMenuVisibility(View.GONE);
