### ISSUE TITLE
How can i use the drawericon?

### ISSUE THREAD

**Issue by ron356** [Quinny898/PersistentSearch#63]
I mean how can I add a listener to it, i'm confused by the searchbox.setMenuListener?? How can i use this please help. I'm a noob

**Comment by Quinny898** [comment]
search.setMenuListener(new MenuListener(){

        @Override
        public void onMenuClick() {
            //Hamburger has been clicked
            Toast.makeText(MainActivity.this, "Menu click", Toast.LENGTH_LONG).show();              
        }

    });

**Comment by ron356** [comment]
Thank you, I have a question again is this correct? I am trying to use the
onPicassoListener, but doesn't seem to be working on BasicImageButtonsCard?
:/

final BasicImageButtonsCardProvider provider = new
Card.Builder(getActivity())

        .setTag("BASIC_IMAGE_BUTTON_CARD")
        .withProvider(BasicImageButtonsCardProvider.class)
        .setDescription(description)


        .setDrawable(R.drawable.try_new)
        .setOnPicassoImageLoadingListener(new
TextCardProvider.OnPicassoImageLoadingListener() {
            @Override
            public void onImageLoading(@NonNull final RequestCreator
requestCreator) {
                requestCreator
                        .resize(40, 70)
                        .centerInside();
            }
        })
        .setTitle(title)
        .setLeftButtonText("Delete")
        .setLeftButtonTextColor(Color.parseColor("#E0E0E0"))
        .setRightButtonTextColor(Color.parseColor("#616161"))
        .setRightButtonText("Add more");

provider.setOnLeftButtonClickListener(new OnButtonClickListener() {
    @Override
    public void onButtonClicked(final View view, final Card card) {
        Intent intent = new Intent(getActivity(),
IndividualProductActivity.class);
        startActivity(intent);


        Log.d("Delete", "Add more");
    }
});
provider.setOnRightButtonClickListener(new OnButtonClickListener() {
    @Override
    public void onButtonClicked(final View view, final Card card) {
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity());
        builder.setMessage("Are you sure you want to delete this
product from your cart?")
                .setTitle("Delete from cart")
                .setPositiveButton("Yes", new
DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        dialog.dismiss();
                    }
                })
                .setNegativeButton("No", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        dialog.dismiss();
                    }
                });
        ;

        AlertDialog dialog = builder.create();
        dialog.show();
    }
});
