### ISSUE TITLE
What if I don't need hamburger?

### ISSUE THREAD

**Issue by Blyabtroi** [Quinny898/PersistentSearch#65]
Thank you for a great component!

What if I don't need hamburger? How to change it to an arrow, for example?

**Comment by Quinny898** [comment]
/***
	 * Set the image drawable of the drawer icon logo (do not set if you have not hidden the menu icon)
	 * @param icon Icon
	 */
	public void setDrawerLogo(Drawable icon) {
		drawerLogo.setImageDrawable(icon);
	}
	
	public void setDrawerLogo(Integer icon) {
		setDrawerLogo(getResources().getDrawable(icon));
	}

**Comment by Blyabtroi** [comment]
Also I need to add 
`search.setMenuVisibility(View.INVISIBLE);`

which leaves me without the ability to use

`search.setMenuListener();`.

Is it a correct behaviour? If so its a little bit inconvenient :)

**Comment by Quinny898** [comment]
It should work with that, you won't need the invisible bit

**Comment by Blyabtroi** [comment]
Here is code
        `search = (SearchBox) findViewById(R.id.searchbox);

        search.setDrawerLogo(R.drawable.ic_up);

        search.setMenuListener(new SearchBox.MenuListener() {

            @Override

            public void onMenuClick() {

                finish();

            }

        });`

which gives me the icon R.drawable.ic_up above the hamburger.

If I make the hamburger invisible (search.setMenuVisibility(View.INVISIBLE);) I lost search.setMenuListener() functionality.

**Comment by cladera** [comment]
+1

**Comment by MrBrightside29** [comment]
Any update on this?

**Comment by Blyabtroi** [comment]
No, I used my own code.
