### ISSUE TITLE
classes are not reachable after update to 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by sosite** [Quinny898/PersistentSearch#66]
After update to 1.1.0-SNAPSHOT I haven't any class from `com.quinny898.library.persistentsearch` package - bug or a feature? o.O

**Comment by Quinny898** [comment]
Try restarting Android Studio, that often helps

**Comment by sosite** [comment]
Finally `clean project` worked. Sometimes I thinking which IDE is more buggy - but then I remind that Eclipse just exit on any error ;)
