### ISSUE TITLE
Not able to build using this library getting error as "Duplicate File" for ic_more_vert_black_24dp.png icon

### ISSUE THREAD

**Issue by poojadeshpande91** [Quinny898/PersistentSearch#69]
Following is the error being shown while building the gradle file

app\build\intermediates\res\debug\drawable-hdpi-v4\ic_more_vert_black_24dp.png: error: Duplicate file.
app\build\intermediates\res\debug\drawable-hdpi\ic_more_vert_black_24dp.png: Original is here. The version qualifier may be implied.

We are also using another library "cardslib" by "gabrielemariotti" which also has this icon.

**Comment by Quinny898** [comment]
There's not much I can really do about that, I'm not changing the whole library's name for the sake of one case.

**Comment by ajans** [comment]
You could try to rename the png-file, I think that would help.

**Comment by poojadeshpande91** [comment]
Hi ajans, 

I did that, but every-time we build the project, png-files will be downloaded again by gradle and problem does not solve.

**Comment by ajans** [comment]
@poojadeshpande91 thank you for your answer, have you tried moving this png-file into your project-resources?

According to this doc-page from google about resource merging, this should take precedence above library dependencies.

http://tools.android.com/tech-docs/new-build-system/resource-merging

BTW, the comment about renaming the png was adressed to @Quinny898, I think he could rename the png-resource to enable compatibility with the cardslib-library. @Quinny898 I don't understand why you think you have to rename the whole library to fix this?
