### ISSUE TITLE
Library Integration Errors

### ISSUE THREAD

**Issue by kmuralidharan91** [Quinny898/PersistentSearch#7]
@MichaelEvans @Quinny898 ::: When i follow the instructions given in readme i facing 9 errors in my sample project.
Can you please make the readme (using the library) more easier for android beginners and also a demonstration video if possible.

**Comment by Quinny898** [comment]
What errors do you get?

**Comment by kmuralidharan91** [comment]
Methods to implement the library to your android studio project.
![screen shot 2015-03-24 at 12 24 33 pm](https://cloud.githubusercontent.com/assets/7802406/6796926/4910d722-d221-11e4-833e-86f629d091ac.png)
![screen shot 2015-03-24 at 12 25 20 pm](https://cloud.githubusercontent.com/assets/7802406/6796928/4913bad2-d221-11e4-83e8-13c858b41e90.png)
![screen shot 2015-03-24 at 12 26 00 pm](https://cloud.githubusercontent.com/assets/7802406/6796931/491adae2-d221-11e4-9024-8e8880021324.png)
![screen shot 2015-03-24 at 12 26 29 pm](https://cloud.githubusercontent.com/assets/7802406/6796927/4912316c-d221-11e4-8fb4-2359022520a1.png)
![screen shot 2015-03-24 at 12 26 42 pm](https://cloud.githubusercontent.com/assets/7802406/6796929/49143854-d221-11e4-930f-9afd5637d568.png)
![screen shot 2015-03-24 at 12 26 53 pm](https://cloud.githubusercontent.com/assets/7802406/6796930/49150ea0-d221-11e4-9801-8940a260ca5a.png)
