### ISSUE TITLE
Gradle build failed with "nineoldandroids" dependency error

### ISSUE THREAD

**Issue by sudam-chavan** [Quinny898/PersistentSearch#96]
Build error:

> Could not resolve all dependencies for configuration ':presentation:_debugCompile'.
   > Could not find any matches for com.nineoldandroids:library:2.4.0+ as no versions of com.nineoldandroids:library are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/nineoldandroids/library/maven-metadata.xml
         https://jcenter.bintray.com/com/nineoldandroids/library/
         https://oss.sonatype.org/content/repositories/snapshots/com/nineoldandroids/library/maven-metadata.xml
         https://oss.sonatype.org/content/repositories/snapshots/com/nineoldandroids/library/
         file:/Users/sudam/softwares/android-sdk/extras/android/m2repository/com/nineoldandroids/library/maven-metadata.xml
         file:/Users/sudam/softwares/android-sdk/extras/android/m2repository/com/nineoldandroids/library/
         file:/Users/sudam/softwares/android-sdk/extras/google/m2repository/com/nineoldandroids/library/maven-metadata.xml
         file:/Users/sudam/softwares/android-sdk/extras/google/m2repository/com/nineoldandroids/library/
     Required by:
         appsurfer_app:presentation:unspecified > com.quinny898.library.persistentsearch:library:1.1.0-SNAPSHOT

**Comment by Amiit-Kkumar** [comment]
Getting the same error while building. It was working fine till yesterday.

**Comment by goyourfly** [comment]
Me too

**Comment by Amiit-Kkumar** [comment]
the library com.nineoldandroids:library:2.4.0+ is deprecated... download the jar file of library and include in your project for a quick fix.

**Comment by sosite** [comment]
Except using a jar I also must exclude nineoldandroids from lib like this:
```
compile ('com.quinny898.library.persistentsearch:library:1.1.0-SNAPSHOT') {
    exclude group: 'com.nineoldandroids'
}
```

**Comment by GauthierRoomDotMe** [comment]
Putting mavenCentral() in Build.gradle as such solved it for us : 
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
    }
}
```

**Comment by sudam-chavan** [comment]
Adding just mavenCentral does not resolve the issue. I need to modify gradle file like below

repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
    }

**Comment by nealsanche** [comment]
Just ran into this issue today. jcenter must be having a bad day. Adding mavenCentral() as described above worked for me.

**Comment by andredelgado** [comment]
adding mavenCentral() fix the issue.

**Comment by koustuvsinha** [comment]
same issue. why is the dev using a deprecated library anyway? no alternatives?

**Comment by Quinny898** [comment]
For compatibility
Adding mavenCentral fixes this, it's not an issue with my library
